import React, {useMemo} from 'react';
import QRCode from 'qrcode';
import {interpolate} from 'remotion';
import {MONO, SANS} from '../fonts';
import {BADGE, BADGE_TOP, QR_PX, REPO_SHORT, REPO_URL, TOOL_NAME} from '../layout';
import {C} from '../theme';

const MARGIN = 2; // quiet-zone modules around the code

/** The repo URL as a QR code, generated by the qrcode package at build time. */
export const QR: React.FC<{size: number}> = ({size}) => {
  const {n, path} = useMemo(() => {
    const code = QRCode.create(REPO_URL, {errorCorrectionLevel: 'L'});
    const {size: count, data} = code.modules;
    let d = '';
    for (let y = 0; y < count; y++) {
      for (let x = 0; x < count; x++) {
        if (data[y * count + x]) d += `M${x + MARGIN} ${y + MARGIN}h1v1h-1z`;
      }
    }
    return {n: count + MARGIN * 2, path: d};
  }, []);
  return (
    <svg width={size} height={size} viewBox={`0 0 ${n} ${n}`} shapeRendering="crispEdges" style={{display: 'block'}}>
      <rect width={n} height={n} fill="#fff" />
      <path d={path} fill="#000" />
    </svg>
  );
};

/**
 * Name, short URL and QR, bottom-right in every frame. `grow` (0..1) moves it
 * to the middle of the end card and scales it up.
 */
export const Badge: React.FC<{grow: number}> = ({grow}) => {
  const corner = {x: 1920 - BADGE.margin - BADGE.w, y: BADGE_TOP};
  const scale = interpolate(grow, [0, 1], [1, 1.35]);
  const centre = {x: (1920 - BADGE.w * 1.35) / 2, y: 690};
  const x = interpolate(grow, [0, 1], [corner.x, centre.x]);
  const y = interpolate(grow, [0, 1], [corner.y, centre.y]);
  return (
    <div
      style={{
        position: 'absolute',
        left: x,
        top: y,
        width: BADGE.w,
        height: BADGE.h,
        transform: `scale(${scale})`,
        transformOrigin: '0 0',
        display: 'flex',
        alignItems: 'center',
        gap: 18,
        padding: 12,
        boxSizing: 'border-box',
        borderRadius: 18,
        background: 'rgba(13,17,25,0.82)',
        border: `1px solid ${C.edge}`,
        boxShadow: '0 12px 40px rgba(0,0,0,0.45)',
      }}
    >
      <div style={{borderRadius: 8, overflow: 'hidden', flex: `0 0 ${QR_PX}px`}}>
        <QR size={QR_PX} />
      </div>
      <div style={{minWidth: 0}}>
        <div style={{fontFamily: SANS, fontWeight: 800, fontSize: 30, color: C.text, letterSpacing: -0.5}}>{TOOL_NAME}</div>
        <div style={{fontFamily: MONO, fontSize: 17, color: C.cyan, marginTop: 8}}>{REPO_SHORT}</div>
        <div style={{fontFamily: SANS, fontSize: 15, color: C.muted, marginTop: 8}}>open source · scan for the repo</div>
      </div>
    </div>
  );
};
